### ISSUE TITLE
INT/VAR file written as DSK/VAR

### ISSUE THREAD

**Issue by christopherkobayashi** [endlos99/xdt99#1]
I've found something interesting while using xdm99.py (good work, by the way) to convert disks to 80-track DSSD images.

If the file on disk is INT/VAR, it is extracted correctly when TIFILES header is used (hex follows):

<code>
00000000  07 54 49 46 49 4c 45 53  00 01 82 03 0a 50 01 00  |.TIFILES.....P..|
</code>

Note the flag at offset 0x0a is correct (0x82 for INT/VAR).

If this file is written to an image, then re-read, it now looks like this:

<code>
00000000  07 54 49 46 49 4c 45 53  00 01 80 03 0a 50 01 00  |.TIFILES.....P..|
</code>

... and the flag is now 0x80, for DSK/VAR.

I've tracked this down to what appears to be a typo on line 481 of xdm99.py, which reads:

self.flags = ord(header[0x0A]) & 0x82

... and I think it should read:

self.flags = ord(header[0x0A]) & 0x83

I think this is incorrect, because it masks away the bit that indicates that the file is integer.  Changing this results in a correct file type on the written file.  I have not tested to see if the data itself is now correct.

Was this an error, or was INT/VAR intentionally disabled?

Thanks,

-- Chris

**Comment by christopherkobayashi** [comment]
"internal", not "integer".  It's late, sorry.

**Comment by endlos99** [comment]
Hello Chris,

Thanks for the bug report -- you're absolutely right, I accidentally masked the DIS/INT bit for TIFiles.  It should be 0x83, just as you wrote.

I fixed xdm99.py, and the correction will also be included in the next release of xdt99.

Ralph

**Comment by christopherkobayashi** [comment]
On Tue, Dec 29, 2015 at 10:13:53AM -0800, Ralph Benzinger wrote:

> Thanks for the bug report -- you're absolutely right, I accidentally masked the DIS/INT bit for TIFiles.  It should be 0x83, just as you wrote.

Oh, neat.  It's nice to be right sometimes.

There's another slight issue with xdm99.py ... when using --set-geometry to
force a "rare" format (80-track DSSD, in this case), the disk constructor still
emits a "Sector count mismatch" because the constructor is called before the
track count is overridden by --set-geometry.

I haven't filed a bug report on this because I don't have a good fix for it
yet.  The constructor is the right place to do sanity-checks, but the override
needs to happen before the constructor is called, and I'm not sure how to do
that just yet.

Thanks for the quick action on the INT issue,

## 

-- Chris
   GPG key fingerprint 603A 9892 C54E 0D77 0F0F  D88A B061 38E3 7BF0 7BE8

**Comment by endlos99** [comment]
Thanks for the hint, I've put it in my backlog for xdm99.  Anything non-40-track is somewhat experimental, as I don't have any personal use for that.
