### ISSUE TITLE
Can't extract files with slash in the name

### ISSUE THREAD

**Issue by peberlein** [endlos99/xdt99#15]
Attempting to extract all files from a disk, and a name contains a slash:

    xdm99.py -i ../marvin.dsk 
    
    MARVIN    :     1173 used  267 free   360 KB  2S/2D 40T  18 S/T
    ----------------------------------------------------------------------------
    9919SFX/S     17  DIS/VAR 80    3930 B  120 recs                         
    CHARS/S       33  DIS/VAR 80    8139 B  149 recs                         
    ...

    xdm99.py -e '*' -t ../marvin.dsk 
    Error: [Errno 2] No such file or directory: 'name2/s.tfi'

Perhaps it could translate slashes to a periods in the filename?

**Comment by endlos99** [comment]
Almost on the anniversary day of this ticket, I fixed this issue in the latest version of xdm99.  Thanks!
