### ISSUE TITLE
TMS99105/110 OPCODES

### ISSUE THREAD

**Issue by AlexanderAdelAU** [endlos99/xdt99#22]
Hello - just for your info, some of the opcodes associated with the TMS99105 are missing, for example

TMB	
TCMB
TSMB

Thanks

**Comment by endlos99** [comment]
Good idea; I'll add them in the next release.

**Comment by endlos99** [comment]
I did forget to add the TMS99000 (covers both 99105 and 99110) opcodes to the current release 3.1.0, but I did add them afterwards.  Since I have no TMS99000 reference, could you please check if syntax and output is correct?  I'll then push the additions to GitHub (not as a separate release, but for downloading).

[as99000.zip](https://github.com/endlos99/xdt99/files/5824333/as99000.zip)

**Comment by endlos99** [comment]
Another question is if all mnemonics of the 9900 are implemented identically in the 99000.  Worded differently, is there a 9900 instruction that would be encoded differently in the 99000?  I didn't compare datasheets, as that would take quite a while.

**Comment by AlexanderAdelAU** [comment]
Thanks Ralph, and sorry for the late reply.    It is late here, but I will look at these tomorrow if I may.   I have been using the tool quite a bit recently and am keen to help with any upgrades.

 

Regards

 

Alex

**Comment by endlos99** [comment]
No rush, Alex!  Take your time, I have plenty of other stuff to do. :-)

**Comment by endlos99** [comment]
I pushed the 99000/105 support to GitHub now.  To use it, please copy the xas99.py executable directly for now, as I still have to make a new release some time later.

If you find anything wrong, please let me now.

**Comment by AlexanderAdelAU** [comment]
Great, thanks for following up Ralph.   I did try and go back to the list of issues I had but could not remember which one concerned me at the time.   Fortunately the issues that I found were easy to recognise and did not impede me.  

 

Anyway, thanks again and I will keep in touch.

 

 

Thanks

 

Alex
