### ISSUE TITLE
v3 SAVE doesn't pad bank binaries

### ISSUE THREAD

**Issue by peberlein** [endlos99/xdt99#23]
I was relying on "SAVE >6000,>8000" padding the banks to full 8K when writing the binaries in the previous version of xas99.py.  Would you please consider adding a command-line option in v3 to re-enable the padding mode?
Edit: My eventual goal is to be able to create banked cartridges with minimal fuss.  Having padded 8K banks allows me to "cat" them together into a single .bin file.  Maybe instead a better solution would be to make the "xas99.py -cart" option work for banked cartridges, with an extra option to switch between rpk and bin format.  I'll try that doing myself first, and send a pull request if I get it working.

**Comment by endlos99** [comment]
I was weighing whether to pad (or rather make SAVE adding zeros to the range) or not, and eventually decided on not padding, because it was blowing up my examples.

But I agree that we need some way of doing that in the assembler itself.  I'll think of something.

**Comment by peberlein** [comment]
This is what I came up with: a new option -B for "binary cart image with zero-padded banks" which perfectly solves the need I have to zero-pad all the banks and concat them into a single file.  This file can be used directly with Classic99 or FinalGROM99, or zipped into a rpk for MAME.  What do you think?

```
diff --git a/xas99.py b/xas99.py
index 375dc76..8493ebb 100755
--- a/xas99.py
+++ b/xas99.py
@@ -2665,6 +2665,8 @@ def main():
                      help='create program image (E/A option 5)')
     cmd.add_argument('-c', '--cart', action='store_true', dest='cart',
                      help='create MESS cart image')
+    cmd.add_argument('-B', '--bincart', action='store_true', dest='bincart',
+                     help='create binary cart image with zero-padded banks')
     cmd.add_argument('-t', '--text', dest='text', nargs='?', metavar='<format>',
                      help='create text file with binary values')
     cmd.add_argument('--embed-xb', action='store_true', dest='embed',
@@ -2714,7 +2716,7 @@ def main():
     errors = False
     target = ('image' if opts.image else
               'cart' if opts.cart else
-              'bin' if opts.bin else
+              'bin' if opts.bin or opts.bincart else
               'xb' if opts.embed else
               'obj')
 
@@ -2798,6 +2800,15 @@ def main():
                 else:
                     name = barename + addr_tag + bank_tag + '.dat'
                 out.append((name, text, 'w'))
+        elif opts.bincart:
+            banksize = program.saves[0][1] - program.saves[0][0]
+            binaries = linker.generate_binaries()
+            image = bytes()
+            for bank, save, addr, data in binaries:
+                print(f"Bank {bank}: {len(data)} bytes")
+                image += data + bytes([0] * (banksize - len(data)))
+            name = opts.output or barename + '.bin'
+            out.append((name, image, 'wb'))
         elif opts.cart:
             data, layout, metainf = linker.generate_cartridge(name)
             output = opts.output or barename + '.rpk'
```
Edit: output name was not being set, and padding wasn't working

**Comment by endlos99** [comment]
Thanks for the patch, but v3.1.0 restored the old behavior of using the full address range of SAVEs.
