### ISSUE TITLE
Error on host with default python2 interpreter

### ISSUE THREAD

**Issue by MirrorPusher** [endlos99/xdt99#29]
Scripts break on host that still has python2 as default system interpreter.

I propose that the shebang in the python script specifies the major python version to use.

`#!/usr/bin/env python3`

instead of

`#!/usr/bin/env python`

**Comment by endlos99** [comment]
Yes, will do.  I thought to remember that you shouldn't include the version, but PEP 394 disagrees.

**Comment by endlos99** [comment]
I changed the executable name to `python3`.

BTW, are you on Windows?  I think my main motivation for not including the version was that Windows Python didn't support versioned `python`, but maybe that changed now.
