### ISSUE TITLE
Options like "-p" and "-e" need "-n", although this is unnecessary.

### ISSUE THREAD

**Issue by christopherkobayashi** [endlos99/xdt99#3]
Subject says it all, really, but I'll paste a test case.

Given this disk image:

[17:40:55] dhcp11-118:~/unix/xdt99$ ./xdm99.py ti-dsdd-v9t9.dsk 
## USGRP1085A:     229 used  131 free   90 KB  1S/1D  40 TpS

*ARTICLE      26  DIS/VAR 80    6312 B  113 recs  
*README1st    22  DIS/VAR 80    5336 B   94 recs  
DSDD2532      17  PROGRAM       4096 B  
DSDD2564      33  PROGRAM       8192 B  
EVM9118/1     33  PROGRAM       8192 B  
EVM9118/2     33  PROGRAM       8192 B  
EVM9118/3     33  PROGRAM       8192 B  
G99110        30  PROGRAM       7230 B                                   

... this fails:

[17:41:03] dhcp11-118:~/unix/xdt99$ ./xdm99.py -p '*ARTICLE' ti-dsdd-v9t9.dsk 
usage: xdm99.py [-h] [-v] [-i | -p <name> [<name> ...] | -e <name>
                [<name> ...] | -a <file> [<file> ...] | -r <old>:<new>
                [<old>:<new> ...] | -d <name> [<name> ...] | -Z <sectors> |
                --set-geometry <geometry> | -C | -R | -S <sector> | -P <file>
                [<file> ...] | -T <file> [<file> ...] | -F <file> [<file> ...]
                | -I <file> [<file> ...]] [-t] [-9] [-f <format>] [-n <name>]
                [-X <size>] [-o <file>] [-q]
                [filename]
Error: Missing disk image

... but this works:

[17:41:22] dhcp11-118:~/unix/xdt99$ ./xdm99.py -p '*ARTICLE' -n bogus ti-dsdd-v9t9.dsk 

```
      11NEW 80 COLUMN CARD FOR THE P-BOX

    IS RELEASED AT THE FAIR IN

            G\TTINGEN
```

(snip printed file)

Same for -e.      -o can be used instead of -n, but that just sets the output filename (in -e case, no effect in -p).  It seems that the minimum requirement for command/argument pairs is three (command/argument to execute, command/argument that is bogus but absent will cause xdm99.pyu to bomb out, and finally the disk image).

This is a bug, yes? :)

**Comment by endlos99** [comment]
There is no real dependency between options, just some commands like -i, -a, -e, -d, -w are mutually exclusive (you cannot add and delete).

But some arguments such as -a, -e, -d allow for multiple filenames, so when you write

    xdm99.py -a file1 file2 w.disk 

it's hard for the argument parser to detect if w.disk is a file to add, or the disk filename.  The parser is not too clever, i.e., it doesn't try all possible combinations and picks the best one.

As a work around, always put the disk upfront.

    xdm99.py w.disk -a file1 file2

That way, there is no confusion.
