### ISSUE TITLE
xas99 add possibility to suppress branch/jump optimization warnings

### ISSUE THREAD

**Issue by MirrorPusher** [endlos99/xdt99#31]
The warning "Possible branch/jump optimization" can cause a lot of noise on large projects where optimization is possible only done at the end of the development cycle.

Would be cool if this warning could be suppressed by a command line parameter in xas99
When getting fancy one could image certain classes of warnings that can be supressed.

**Comment by endlos99** [comment]
You probably know that you can disable *all* warnings with `-q`.

But I'll think about classes of warning (e.g., optimizations, likely errors, ...) and how to disable those only.

**Comment by endlos99** [comment]
In the new release, I group warning into optimizations, usage, and unused symbols, and each category can be disabled individually, e.g., `--quiet-unused-syms`.

Thanks for the suggestion!
