### ISSUE TITLE
Warning: Unexpected arithmetical precedence with unary minus

### ISSUE THREAD

**Issue by peberlein** [endlos99/xdt99#33]
This new warning showed up with the latest xas99.py.  These arithmetic expressions should be unambiguous.  Seems like the unary minus is causing the warning:

```
> hero.asm <2> 0678 -        AI R5,-8*256
***** Warning: Unexpected arithmetical precedence
> scroll.asm <2> 0234 -        AI R4,(-32*22)-1
***** Warning: Unexpected arithmetical precedence
> scroll.asm <2> 0291 -        AI R4,(-32*22)+1
***** Warning: Unexpected arithmetical precedence
> movobj.asm <2> 0441 -        AI R5,(-32*256)+16
***** Warning: Unexpected arithmetical precedence
```

**Comment by endlos99** [comment]
Yeah, sorry, I missed some cases for that check ...  I hope to release a fix this weekend.

**Comment by peberlein** [comment]
Thank you.  I appreciate all the work you've done lately.

**Comment by endlos99** [comment]
I've pushed a fix for xas99 and xga99 regarding this issue.  I hope I covered all cases now.

Please download xas99 directly, as I'm still waiting for a solution to the IDEA plugin code completion issue before I publish another release.

Thanks for reporting this so quickly!
