### ISSUE TITLE
Documentation on xas99 -I parameter

### ISSUE THREAD

**Issue by MirrorPusher** [endlos99/xdt99#35]
Minor documentation issue.
The documentation is a bit unclear about usage of the -I parameter (that is capital I --> include path option)

Include paths are separated by ","-character but that is not mentioned in the documentation.
There it implies that white space is used  when supplying multiple include paths.
Looking at the source code, solved it for me.

https://endlos99.github.io/xdt99/#xas99

Also perhaps it should be mentioned that -I cannot be provided as part of the XAS99_CONFIG environment variable.

**Comment by endlos99** [comment]
Yes, I'll fix the manual and also remove the space separation.

But -I in XAS99_CONFIG is working for me, as long as the path in -I is either absolute or relative to the directory where xas99 is invoked.  Could you please check again?

**Comment by endlos99** [comment]
Fixed (I hope), please see the documentation on `;` to terminate Xxx_CONFIG definitions.  As for the documentation, I hope it makes sense now.
