### ISSUE TITLE
xdt 3.5.0 xas99 crashed with ValueError due to invalid pragma

### ISSUE THREAD

**Issue by FilipVanVooren** [endlos99/xdt99#36]
Currently switching to the newest xas99 version.

In my source code I have the following line
`jeq   !                     : Block mode inactive, show dialog`

When trying to assemble, it causes xas99 to crash with following error:
`Traceback (most recent call last):
  File "/app/xdt99-3.5.0/xas99.py", line 3500, in <module>
    status = main()
  File "/app/xdt99-3.5.0/xas99.py", line 3397, in main
    asm.assemble(dirname, basename)
  File "/app/xdt99-3.5.0/xas99.py", line 2329, in assemble
    self.assemble_pass_2()
  File "/app/xdt99-3.5.0/xas99.py", line 2349, in assemble_pass_2
    self.pragmas.process(self, pragmas)
  File "/app/xdt99-3.5.0/xas99.py", line 2032, in process
    name, value = pragma.split('=')
ValueError: not enough values to unpack (expected 2, got 1)`

Doing a print of the pragma in line 2031 gives me:
`BLOCK MODE INACTIVE`

This wasn't an issue before, because the version of xas99 I was using didn't know these kind of pragmas.

Changing the colon to a semicolon fixed the issue 
`jeq   !                     ; Block mode inactive, show dialog`

**Comment by endlos99** [comment]
Yes, this is a bug Rasmus discovered a few days ago.  It's already fixed; please download the latest xas99.py (there is no release yet).
