### ISSUE TITLE
xas99 possibility to write binary file to target directory

### ISSUE THREAD

**Issue by FilipVanVooren** [endlos99/xdt99#37]
I'm using xas99 to assemble my source files with the '-b' option.
The binary file seems to be written to the directory where the xas99 assembler is started?

Is there a possibility to specify the target directory (and target filename)?
I'm currently using a shell script to move the binary to its destination

Perhaps a parameter like "**--ouput-dir**" or "--binary-output-file"
(Kinda like the option '--listing-file')

**Comment by endlos99** [comment]
Thanks for your suggestion, but this is already possible with -o.  You can either supply a filename (which may have a path), or a directory, in which case the default filename is used.  

For example:
`$ xas99.py -b src/asfile.asm -o gen/`
This will create `gen/asfile.bin`.  You can just use `-o gen`, of course.

If you want to change the output file from asfile.bin, you include the filename:
`$ xas99.py -b src/asfile.asm -o gen/game.bin`
This will create `gen/game.bin`.

There's still something to do, however, as this won't work with the list file yet, so I'm keeping the issue open.

**Comment by MirrorPusher** [comment]
Thanks, I wasn't aware of that. That's a great solution.

**Comment by endlos99** [comment]
Ah, I forgot to update this issue -- with the latest version of xdt99, you can specify directories for any output file (-o, -L, -E, ...).
