### ISSUE TITLE
Documentation on xas99 -D parameter

### ISSUE THREAD

**Issue by FilipVanVooren** [endlos99/xdt99#38]
Documentation is a bit unclear about the parameter position of the '-D' parameter. It must be supplied after the source(s) to assemble.
Also in the documentation the parameter is shown before the source file(s), which is apparently no longer correct.

https://github.com/endlos99/xdt99/blob/master/doc/MANUAL.md#xas99

From the documentation:
`$ xas99.py
usage: xas99.py [-h] [-b | -i | -c | -t [<format>] | --embed-xb]
                [-l <file> [<file> ...] | -ll <file> [<file> ...]] [-5] [-18]
                [-s] [-n <name>] [-R] [-C] [-L <file>] [-S] [-E <file>] [-q]
                [-a <addr>] [-I <paths>] [-D <sym=val> [<sym=val> ...]]
                [-o <file>]
                [<source> [<source> ...]]
xas99.py: error: One of <source> or -l/-ll is required.`

**Comment by endlos99** [comment]
Yeah, that whole thing is a pain in the ass.  I think I'll convert the "lists separated by space", which is Python default, to "lists separated by comma" to avoid this restriction about -D and fixing the -h string, which cannot really be changed.

**Comment by endlos99** [comment]
No, I'll keep space as separator, since I don't want to change xdm99, where comma would be really inconvenient.  I'll update the manual instead.

**Comment by endlos99** [comment]
Fixed (I hope), please see the documentation on `;` to terminate Xxx_CONFIG definitions. As for the documentation, I hope it makes sense now.  Regarding the incorrect help string, I mentioned explained that as well. :-/
