### ISSUE TITLE
(bug) files that start with "-" cannot be extracted

### ISSUE THREAD

**Issue by christopherkobayashi** [endlos99/xdt99#4]
Feature request time.  Or maybe a bug report.  

It's advantageous sometimes to extract all files from a disk image.  However, the TI allowed characters that are forbidden in UNIX --  specifically "-".

Normally when extracting, one could iterate in shell through the contents as listed by xdm99 by doing "for filename in ${FILE_LIST}; do xdm99.py -e ${filename} -n bogus --tifiles disk.dsk; done" ... but this won't work for files that start with "-", because they will be treated as the beginning of another argument by xdm99's parser and will fail.

I don't have a good fix for this, or I'd attach one.  Maybe use the same logic as cp/mv/rm using "--" as an extra argument, but transplanted to python?

**Comment by endlos99** [comment]
Sorry for the slow response, it took a while for me to work on xdm99 again.

After thinking about your problem, I think it's not for xdm99 to address this.  For example, this is not a Windows issue, so I'd need to platform-specific code.

I think it's the job of the surrounding tooling to handle this.  On Linux, you could preface each filename with ./ to disable interpreting as option.

But I'll think more about using xdt99 in scripts.
