### ISSUE TITLE
No directive to repeat a block

### ISSUE THREAD

**Issue by litwr2** [endlos99/xdt99#41]
I have missed something like this construct
```
.rept 10
...
.endr
```
which is quite common for other assemblers.

**Comment by endlos99** [comment]
That should be easy to add.  But may I ask what you intend to use this feature for?  Repeating data?  Loop unrolling?

**Comment by litwr2** [comment]
I don't know of any other assembler that omits this feature. It is hardly worth adding anything else to your list, but these two cases are quite important. Anyway thanks for your very useful programs.

**Comment by endlos99** [comment]
Thanks for your suggestion.  I've added .rept/.endr to xas99 and xga99 as of version 3.5.4.
