### ISSUE TITLE
Feature Request: xbas99 pre-processing to convert long names to short names for limits in TI env tools

### ISSUE THREAD

**Issue by mcvde** [endlos99/xdt99#44]
Seemingly the best XB compiler in the TI environment is the XB Compiler named COMPILER by senior_falcon. This is packaged in the juwel994 package along with an assembler also aptly named ASSEMBLER. Both tools are limited to 6 characters for names, in particular subprogram names. 

Writing software using modern techniques usually yields libraries with methods, resulting in final method names in the format lib_method. 

Something as simple as renaming methods to Cxxxx would be sufficient. And as a bonus perhaps adding comments that describe the name change.

Example:

 call clear
 call main
 end

 sub main
    call print_line ("hello world!")
 subend

 sub print_line (a$)
    print a$
 subend

converts to:

 call clear
 ! call main
 call C0001
 end

 ! main
 sub C0001
    ! call print_line
    call C0002 ("hello world!")
 subend

 ! print_line
 sub C0002 (a$)
    print a$
 subend

**Comment by endlos99** [comment]
Already implemented.  But do you have the exact name of the compiler, or could you provide me a link to its homepage?  Putting "XB compiler by senior_falcon" into the manual might not make much sense to people.  (I know of XB256 -- is that a different one?)

**Comment by mcvde** [comment]
Yes I agree on the manual bit. It's a different compiler.

senior_falcon is Harry Wilhelm.

When the compiler program is started, it states:
EXTENDED BASIC COMPILER
Harry Wilhelm 2018

**Comment by mcvde** [comment]
That's great you have it implemented! I look forward to using it. It's nice that you are providing tooling and making it available to the general public for anyone interested.

**Comment by endlos99** [comment]
I've just pushed a new version of xbas99.py to the xdt99 repository.  Please see [this file](https://github.com/endlos99/xdt99/blob/master/doc/CHANGES.md) for a description of the new features.

If everything is OK, I'll make a new release on the weekend.

**Comment by mcvde** [comment]
Cool. Again, looking forward to this change.

**Comment by mcvde** [comment]
I found time to pull down from the master. It didn't have your changes but I see you said you'd push perhaps on the weekend. I'll watch for an update.

**Comment by endlos99** [comment]
Sorry, you need to download this file: https://raw.githubusercontent.com/endlos99/xdt99/master/xbas99.py.

Release will follow later.

**Comment by mcvde** [comment]
Excellent. Thanks for the link.
