### ISSUE TITLE
Two successive labels on consecutive rows cause error

### ISSUE THREAD

**Issue by petersobolev** [endlos99/xdt99#5]
_....
qq:
nextblock:
...._

returns  error:
<1> 0174 - nextblock:
****\* Invalid continuation for label

(xas 1.5.0)

**Comment by endlos99** [comment]
This is a restriction of so-called continuation labels, i.e., labels with a ":".  Unfortunately, you cannot have two of them in a row if no statement is present.

The easy solution, however, is to simply drop the ":" at the end of the label.

If you want to learn about the difference between "label" and "label:", please check the manual for "label continuations".
