### ISSUE TITLE
Jumpstart and EA difference

### ISSUE THREAD

**Issue by petersobolev** [endlos99/xdt99#8]
Could you explain in detail how "jumpstart" code works (process of loading) comparing to Editor/Assembler option 3(5) ?
Sometimes I see a strange things: my code compiled without errors and runs ok with jumpstarting, but doesn't load with Editor/Assembler option 3.
I know at least two reasons for that:
1. Second "end" directive somewhere in source (E/A trying to load code but after some delay clears screen and offer to enter name again, without errors). Jumpstart loads ok.
2. Some DEFs (def timingin, def timingout) in included tiplayer source (E/A reports "duplicate definition")
3. ... not sure, maybe there were another cases

Perhaps it's all my mistakes, but I need to know why it not reported as such by XAS. It was really hard to understand reason why EA fails (especially in first case). And why it was loaded ok with "jumpstart".

Thanks!

**Comment by endlos99** [comment]
The Jumpstart format is a raw memory dump, such as "-b" would produce.  All the Jumpstart cart does is loading the dump into memory, and running it.

The E/A module uses a "linking loader", i.e., it not only loads code, but it also resolves symbols.  Some symbols, in particular VSBW etc. are predefined by the loader, and your code (for EA3) should not define them, but reference them with `REF`.

Code intended for a cartridge, on the other hand, can't rely on those symbols (and the code behind them), so it needs to define its own VSBW routines.  This will yield "duplicate definitions" if you export those symbols with `DEF`.

So you basically need to decide how you want to run your code.  If you want to support several methods you can use `.ifdef` and check for predefined symbols `_xas_cart` etc.

If this doesn't explain the behavior you observe then please post some sample code.

**Comment by petersobolev** [comment]
Thank you, now it is clear!
