### ISSUE TITLE
.img files limited to 8192 bytes?

### ISSUE THREAD

**Issue by petersobolev** [endlos99/xdt99#9]
Can't generate .img file more than 8192 bytes.

I've created small source to demonstrate problem:

```
------------
          def  start
start:
          jmp start
mainlogo_attrs:
           bcopy "FORCE.TIAC"    ; color data (6144 bytes binary)
mainlogo_patterns:
           bcopy "FORCE.TIAP"    ; pattern data (6144 bytes binary)
        end    start
-----------
```

"xas99.py -R -i testimg.a99" created file testimg.img with size 8192 bytes.

(.obj files are correct and works ok. .lst file also correct - with >3000 as last address )

**Comment by endlos99** [comment]
The 8192 byte limit is intensional.  The "-i" option produces images for the Editor/Assembler module option 5, which expects programs in 8K chunks.  For your example, you should also get a second file "testimh.img", which contains the rest of your program.  If you add both files to a disk image, e.g.,

`xdm99.py work.dsk -X sssd -a testim?.img -n TESTIMG`

then you can load the entire program with DSK1.TESTIMG in E/A5.

Note that each chunk has some header data, so you cannot simply concatenate the files.

If you want a single file you could use the "-b" option instead.
